#iskeyword
'''
import keyword
print(keyword.iskeyword("True"))
print(keyword.iskeyword("Import"))
print(keyword.iskeyword("if"))
print(keyword.iskeyword("ELSE"))
print(keyword.iskeyword("int"))

'''
#isidentifier
'''
print('num1'.isidentifier())
print('9a'.isidentifier())
print('a_1'.isidentifier())
print('_1a'.isidentifier())
print('a_'.isidentifier())
print('a+'.isidentifier())
#9.isinstance
'''
#isinstance
'''
print(isinstance(34,int))
print(isinstance('a',int))
print(isinstance(3.4,float))
print(isinstance(34-4j,(int,complex)))
print(isinstance(True,(int,complex)))
print(isinstance(6.7,(int,complex)))
'''
